### DISCUSSION TITLE
Testing against instance with SSL

### DISCUSSION THREAD

**Discussion by stefanak-michal** [thingsdb/ThingsDB#368] [Q&A] [answered]
Hi.

I would like to test socket connection with SSL and I'm thinking about using playground instance. I'm not sure if playground instance are turned off after some time of inactivity. So that would be my first question. Are they?

If yes then the title of this discussion takes place. Can I somehow request status of playground instance? I see in node info HTTP status port 8080 but I'm unable to create url which will work. What format should url have to get [readiness and liveness](https://docs.thingsdb.io/v1/getting-started/readiness-liveness/) ?

Maybe in the end I would like to ask other question to avoid all this trouble. It is possible to run thingsDB in container (docker) with certificate so I can test ssl connection with it? I don't see anything related to this in docs.

**Comment by joente** [comment]
1. Playground instances will stay alive and they are not turned off. Keep in mind however that we might bring the the playground offline for short periods like an hour as we do not consider this as a critical environment.
2. If you want your own playground and test TLS/SSL, you can use [tlsproxy](https://github.com/cesbit/tlsproxy) with ThingsDB. 
3. I'm not sure if I understand the question about readiness/liveness correct, but this is what we do in Kubernetes: 
```
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
```
4. It is rather simple to create a docker container with TLS/SSL support, just by using the "tlsproxy" mentioned earlier. Can you create one? (If you need help, just reply)
