### ISSUE TITLE
Crashes when running in Kubernetes

### ISSUE THREAD

**Issue by rickmoonex** [thingsdb/ThingsDB#376]
**Describe the bug**
I'm trying to move my docker deployment of ThingsDB to Kubernetes. I have modified the StatefulSet documented under the GKE documentation. But the container becomes trapped in a crash loop with no useable logs. Even after stripping it down to a minimal Pod deployment it experiences the same issue.

**To Reproduce**
1. Deploy the following StatefulSet to K8s:
```yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: thingsdb
  labels:
    app: thingsdb
spec:
  selector:
    matchLabels:
      app: thingsdb
  serviceName: thingsdb
  replicas: 1
  updateStrategy:
    type: RollingUpdate
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: thingsdb
    spec:
      terminationGracePeriodSeconds: 90
      dnsConfig:
        searches:
        - thingsdb.default.svc.cluster.local
      tolerations:  # wait 10 miniutes as synchronizing might take some time
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 600
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 600
      containers:
      - name: thingsdb
        image: ghcr.io/thingsdb/node:latest # Latest version at the time of writing
        imagePullPolicy: Always
        args: ["--deploy"]  # Tells ThingsDB it will be deployed in Kubernetes
        env:
        - name: THINGSDB_HTTP_STATUS_PORT
          value: "8080"
        - name: THINGSDB_HTTP_API_PORT
          value: "9210"
        - name: THINGSDB_STORAGE_PATH
          value: /mnt/thingsdb/
        - name: THINGSDB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        ports:
        - name: status
          containerPort: 8080
        - name: client
          containerPort: 9200
        - name: http
          containerPort: 9210
        - name: node
          containerPort: 9220
        volumeMounts:
        - name: data
          mountPath: /mnt/thingsdb
        resources:
          requests:
            memory: 512Mi
        livenessProbe:
          httpGet:
            path: /healthy
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
```
2. Deploy the 'minimal' Pod deployment tot K8s:
```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: thingsdb
  labels:
    app: thingsdb
spec:
  containers:
    - name: thingsdb
      image: ghcr.io/thingsdb/node:latest
      args: 
        - "--init"
        - "--log-level debug"
      ports:
        - containerPort: 9200
```

**Expected behavior**
The ThingsDB container should start and run as expected. Or at least show some debugging information.

**Screenshots**
```bash
kubectl get pods
NAME                READY   STATUS             RESTARTS        AGE
thingsdb            0/1     CrashLoopBackOff   6 (3m54s ago)   9m32s
thingsdb-sample-0   0/1     CrashLoopBackOff   11 (10s ago)    31m
```

```bash
kubectl logs thingsdb
   _____ _   _             ____  _____
  |_   _| |_|_|___ ___ ___|    \| __  |
    | | |   | |   | . |_ -|  |  | __ -|
    |_| |_|_|_|_|_|_  |___|____/|_____|   version: 1.6.0
                  |___|
EOF
```

**Machine/OS:**
 - OS: Ubuntu
 - Version 23.04
 - K8s Version: 1.29.3

**Comment by joente** [comment]
I'm not sure what is wrong with the StatefulSet, however the 'minimal' pod has a small mistake with the `--log-level` argument. _(spaces are not allowed and therefore debug must be given as a separate argument)_

```yaml
---
apiVersion: v1
kind: Pod
metadata:
  name: thingsdb
  labels:
    app: thingsdb
spec:
  containers:
    - name: thingsdb
      image: ghcr.io/thingsdb/node:latest
      args: 
        - "--init"
        - "--log-level"
        - "debug"
      ports:
        - containerPort: 9200
```

I would however expect a different log: something like `"unrecognized argument...."`.

If it still doesn't work after fixing the 'minimal' pod, can you verify the output of the `kubectl describe pod <pod_name>` command?
